version: '3.8'
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=dev
    extra_hosts:
      - host.docker.internal:host-gateway

  db:
    image: mongo
    ports:
      - "27018:27017"
